name: ecashier
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Routing
  auto_route: ^10.0.1

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # State Management
  flutter_bloc: ^9.1.1

  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  awesome_dio_interceptor: ^1.3.0

  # Utilities
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.3
  shared_preferences: ^2.5.0
  dropdown_search: ^6.0.2
  gif: ^2.3.0
  gif_view: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.1.9
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/encode_sans/EncodeSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/encode_sans/EncodeSans-Light.ttf
          weight: 300
        - asset: assets/fonts/encode_sans/EncodeSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/encode_sans/EncodeSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/encode_sans/EncodeSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/encode_sans/EncodeSans-Bold.ttf
          weight: 700
